#    This file was created by
#    MATLAB Deep Learning Toolbox Converter for TensorFlow Models.
#    2024-08-05 03:09:52

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def create_model():
    ImageInputLayer_unnormalized = keras.Input(shape=(48,48,1), name="ImageInputLayer_unnormalized")
    ImageInputLayer = keras.layers.Normalization(axis=(1,2,3), name="ImageInputLayer_")(ImageInputLayer_unnormalized)
    Encoder_Stage_1_Conv_1 = layers.Conv2D(64, (3,3), padding="same", name="Encoder_Stage_1_Conv_1_")(ImageInputLayer)
    Encoder_Stage_1_ReLU_1 = layers.ReLU()(Encoder_Stage_1_Conv_1)
    Encoder_Stage_1_Conv_2 = layers.Conv2D(64, (3,3), padding="same", name="Encoder_Stage_1_Conv_2_")(Encoder_Stage_1_ReLU_1)
    Encoder_Stage_1_ReLU_2 = layers.ReLU()(Encoder_Stage_1_Conv_2)
    Encoder_Stage_1_MaxPool = layers.MaxPool2D(pool_size=(2,2), strides=(2,2))(Encoder_Stage_1_ReLU_2)
    Encoder_Stage_2_Conv_1 = layers.Conv2D(128, (3,3), padding="same", name="Encoder_Stage_2_Conv_1_")(Encoder_Stage_1_MaxPool)
    Encoder_Stage_2_ReLU_1 = layers.ReLU()(Encoder_Stage_2_Conv_1)
    Encoder_Stage_2_Conv_2 = layers.Conv2D(128, (3,3), padding="same", name="Encoder_Stage_2_Conv_2_")(Encoder_Stage_2_ReLU_1)
    Encoder_Stage_2_ReLU_2 = layers.ReLU()(Encoder_Stage_2_Conv_2)
    Encoder_Stage_2_MaxPool = layers.MaxPool2D(pool_size=(2,2), strides=(2,2))(Encoder_Stage_2_ReLU_2)
    Encoder_Stage_3_Conv_1 = layers.Conv2D(256, (3,3), padding="same", name="Encoder_Stage_3_Conv_1_")(Encoder_Stage_2_MaxPool)
    Encoder_Stage_3_ReLU_1 = layers.ReLU()(Encoder_Stage_3_Conv_1)
    Encoder_Stage_3_Conv_2 = layers.Conv2D(256, (3,3), padding="same", name="Encoder_Stage_3_Conv_2_")(Encoder_Stage_3_ReLU_1)
    Encoder_Stage_3_ReLU_2 = layers.ReLU()(Encoder_Stage_3_Conv_2)
    Encoder_Stage_3_MaxPool = layers.MaxPool2D(pool_size=(2,2), strides=(2,2))(Encoder_Stage_3_ReLU_2)
    Encoder_Stage_4_Conv_1 = layers.Conv2D(512, (3,3), padding="same", name="Encoder_Stage_4_Conv_1_")(Encoder_Stage_3_MaxPool)
    Encoder_Stage_4_ReLU_1 = layers.ReLU()(Encoder_Stage_4_Conv_1)
    Encoder_Stage_4_Conv_2 = layers.Conv2D(512, (3,3), padding="same", name="Encoder_Stage_4_Conv_2_")(Encoder_Stage_4_ReLU_1)
    Encoder_Stage_4_ReLU_2 = layers.ReLU()(Encoder_Stage_4_Conv_2)
    Encoder_Stage_4_DropOut = layers.Dropout(0.500000)(Encoder_Stage_4_ReLU_2)
    Encoder_Stage_4_MaxPool = layers.MaxPool2D(pool_size=(2,2), strides=(2,2))(Encoder_Stage_4_DropOut)
    Bridge_Conv_1 = layers.Conv2D(1024, (3,3), padding="same", name="Bridge_Conv_1_")(Encoder_Stage_4_MaxPool)
    Bridge_ReLU_1 = layers.ReLU()(Bridge_Conv_1)
    Bridge_Conv_2 = layers.Conv2D(1024, (3,3), padding="same", name="Bridge_Conv_2_")(Bridge_ReLU_1)
    Bridge_ReLU_2 = layers.ReLU()(Bridge_Conv_2)
    Bridge_DropOut = layers.Dropout(0.500000)(Bridge_ReLU_2)
    Decoder_Stage_1_UpConv = layers.Conv2DTranspose(512, (2,2), strides=(2,2), name="Decoder_Stage_1_UpConv_")(Bridge_DropOut)
    Decoder_Stage_1_UpReLU = layers.ReLU()(Decoder_Stage_1_UpConv)
    Decoder_Stage_1_DepthConcatenation = layers.Concatenate(axis=-1)([Decoder_Stage_1_UpReLU, Encoder_Stage_4_ReLU_2])
    Decoder_Stage_1_Conv_1 = layers.Conv2D(512, (3,3), padding="same", name="Decoder_Stage_1_Conv_1_")(Decoder_Stage_1_DepthConcatenation)
    Decoder_Stage_1_ReLU_1 = layers.ReLU()(Decoder_Stage_1_Conv_1)
    Decoder_Stage_1_Conv_2 = layers.Conv2D(512, (3,3), padding="same", name="Decoder_Stage_1_Conv_2_")(Decoder_Stage_1_ReLU_1)
    Decoder_Stage_1_ReLU_2 = layers.ReLU()(Decoder_Stage_1_Conv_2)
    Decoder_Stage_2_UpConv = layers.Conv2DTranspose(256, (2,2), strides=(2,2), name="Decoder_Stage_2_UpConv_")(Decoder_Stage_1_ReLU_2)
    Decoder_Stage_2_UpReLU = layers.ReLU()(Decoder_Stage_2_UpConv)
    Decoder_Stage_2_DepthConcatenation = layers.Concatenate(axis=-1)([Decoder_Stage_2_UpReLU, Encoder_Stage_3_ReLU_2])
    Decoder_Stage_2_Conv_1 = layers.Conv2D(256, (3,3), padding="same", name="Decoder_Stage_2_Conv_1_")(Decoder_Stage_2_DepthConcatenation)
    Decoder_Stage_2_ReLU_1 = layers.ReLU()(Decoder_Stage_2_Conv_1)
    Decoder_Stage_2_Conv_2 = layers.Conv2D(256, (3,3), padding="same", name="Decoder_Stage_2_Conv_2_")(Decoder_Stage_2_ReLU_1)
    Decoder_Stage_2_ReLU_2 = layers.ReLU()(Decoder_Stage_2_Conv_2)
    Decoder_Stage_3_UpConv = layers.Conv2DTranspose(128, (2,2), strides=(2,2), name="Decoder_Stage_3_UpConv_")(Decoder_Stage_2_ReLU_2)
    Decoder_Stage_3_UpReLU = layers.ReLU()(Decoder_Stage_3_UpConv)
    Decoder_Stage_3_DepthConcatenation = layers.Concatenate(axis=-1)([Decoder_Stage_3_UpReLU, Encoder_Stage_2_ReLU_2])
    Decoder_Stage_3_Conv_1 = layers.Conv2D(128, (3,3), padding="same", name="Decoder_Stage_3_Conv_1_")(Decoder_Stage_3_DepthConcatenation)
    Decoder_Stage_3_ReLU_1 = layers.ReLU()(Decoder_Stage_3_Conv_1)
    Decoder_Stage_3_Conv_2 = layers.Conv2D(128, (3,3), padding="same", name="Decoder_Stage_3_Conv_2_")(Decoder_Stage_3_ReLU_1)
    Decoder_Stage_3_ReLU_2 = layers.ReLU()(Decoder_Stage_3_Conv_2)
    Decoder_Stage_4_UpConv = layers.Conv2DTranspose(64, (2,2), strides=(2,2), name="Decoder_Stage_4_UpConv_")(Decoder_Stage_3_ReLU_2)
    Decoder_Stage_4_UpReLU = layers.ReLU()(Decoder_Stage_4_UpConv)
    Decoder_Stage_4_DepthConcatenation = layers.Concatenate(axis=-1)([Decoder_Stage_4_UpReLU, Encoder_Stage_1_ReLU_2])
    Decoder_Stage_4_Conv_1 = layers.Conv2D(64, (3,3), padding="same", name="Decoder_Stage_4_Conv_1_")(Decoder_Stage_4_DepthConcatenation)
    Decoder_Stage_4_ReLU_1 = layers.ReLU()(Decoder_Stage_4_Conv_1)
    Decoder_Stage_4_Conv_2 = layers.Conv2D(64, (3,3), padding="same", name="Decoder_Stage_4_Conv_2_")(Decoder_Stage_4_ReLU_1)
    Decoder_Stage_4_ReLU_2 = layers.ReLU()(Decoder_Stage_4_Conv_2)
    Final_ConvolutionLayer = layers.Conv2D(2, (1,1), padding="same", name="Final_ConvolutionLayer_")(Decoder_Stage_4_ReLU_2)
    Softmax_Layer = layers.Softmax()(Final_ConvolutionLayer)
    Segmentation_Layer = Softmax_Layer

    model = keras.Model(inputs=[ImageInputLayer_unnormalized], outputs=[Segmentation_Layer])
    return model
